return {
[1] = {slot_id=1,item_id=8449,maneuver="Fire Maneuver",name="Strobe",family="Strobe",has_ability=true,incoming_text="Provoke",recast=30},
[2] = {slot_id=28450,maneuver="Fire Maneuver",name="Tension Spring",family="Tension Spring",has_ability=false,incoming_text="",recast=0},
[3] = {slot_id=38451,maneuver="Fire Maneuver",name="Inhibitor",family="Inhibitor",has_ability=false,incoming_text="",recast=0},
[4] = {slot_id=48452,maneuver="Fire Maneuver",name="Tension Spring II",family="Tension Spring",has_ability=false,incoming_text="",recast=0},
[5] = {slot_id=58453,maneuver="Fire Maneuver",name="Attuner",family="Attuner",has_ability=false,incoming_text="",recast=0},
[6] = {slot_id=68454,maneuver="Fire Maneuver",name="Reactive Shield",family="Reactive Shield",has_ability=true,incoming_text="Unknown",recast=65},
[7] = {slot_id=78455,maneuver="Fire Maneuver",name="Flame Holder",family="Flame Holder",has_ability=false,incoming_text="",recast=0},
[8] = {slot_id=88456,maneuver="Fire Maneuver",name="Heat Capacitor",family="Heat Capacitor",has_ability=true,incoming_text="Unknown",recast=90},
[9] = {slot_id=98457,maneuver="Fire Maneuver",name="Strobe II",family="Strobe",has_ability=true,incoming_text="Provoke",recast=30},
[10] = {slot_id=108458,maneuver="Fire Maneuver",name="Tension Spring III",family="Tension Spring",has_ability=false,incoming_text="",recast=0},
[11] = {slot_id=118459,maneuver="Fire Maneuver",name="Inhibitor II",family="Inhibitor",has_ability=false,incoming_text="",recast=0},
[12] = {slot_id=128460,maneuver="Fire Maneuver",name="Tension Spring IV",family="Tension Spring",has_ability=false,incoming_text="",recast=0},
[13] = {slot_id=138461,maneuver="Fire Maneuver",name="Heat Capacitor II",family="Heat Capacitor",has_ability=true,incoming_text="Unknown",recast=90},
[14] = {slot_id=148462,maneuver="Fire Maneuver",name="Speedloader",family="Speedloader",has_ability=false,incoming_text="",recast=0},
[15] = {slot_id=158463,maneuver="Fire Maneuver",name="Speedloader II",family="Speedloader",has_ability=false,incoming_text="",recast=0},
[16] = {slot_id=168464,maneuver="Fire Maneuver",name="Tension Spring V",family="Tension Spring",has_ability=false,incoming_text="",recast=0},
[17] = {slot_id=178465,maneuver="Fire Maneuver",name="Magniplug",family="Magniplug",has_ability=false,incoming_text="",recast=0},
[18] = {slot_id=188466,maneuver="Fire Maneuver",name="Magniplug II",family="Magniplug",has_ability=false,incoming_text="",recast=0},
[19] = {slot_id=198481,maneuver="Ice Maneuver",name="Mana Booster",family="Mana Booster",has_ability=false,incoming_text="",recast=0},
[20] = {slot_id=208482,maneuver="Ice Maneuver",name="Loudspeaker",family="Loudspeaker",has_ability=false,incoming_text="",recast=0},
[21] = {slot_id=218483,maneuver="Ice Maneuver",name="Scanner",family="Scanner",has_ability=false,incoming_text="",recast=0},
[22] = {slot_id=228484,maneuver="Ice Maneuver",name="Loudspeaker II",family="Loudspeaker",has_ability=false,incoming_text="",recast=0},
[23] = {slot_id=238485,maneuver="Ice Maneuver",name="Tactical Processor",family="Tactical Processor",has_ability=false,incoming_text="",recast=0},
[24] = {slot_id=248486,maneuver="Ice Maneuver",name="Tranquilizer",family="Tranquilizer",has_ability=false,incoming_text="",recast=0},
[25] = {slot_id=258487,maneuver="Ice Maneuver",name="Ice Maker",family="Ice Maker",has_ability=false,incoming_text="",recast=0},
[26] = {slot_id=268488,maneuver="Ice Maneuver",name="Power Cooler",family="Power Cooler",has_ability=false,incoming_text="",recast=0},
[27] = {slot_id=278489,maneuver="Ice Maneuver",name="Loudspeaker III",family="Loudspeaker",has_ability=false,incoming_text="",recast=0},
[28] = {slot_id=288490,maneuver="Ice Maneuver",name="Tranquilizer II",family="Tranquilizer",has_ability=false,incoming_text="",recast=0},
[29] = {slot_id=298491,maneuver="Ice Maneuver",name="Amplifier",family="Amplifier",has_ability=false,incoming_text="",recast=0},
[30] = {slot_id=308492,maneuver="Ice Maneuver",name="Loudspeaker IV",family="Loudspeaker",has_ability=false,incoming_text="",recast=0},
[31] = {slot_id=318493,maneuver="Ice Maneuver",name="Tranquilizer III",family="Tranquilizer",has_ability=false,incoming_text="",recast=0},
[32] = {slot_id=328494,maneuver="Ice Maneuver",name="Amplifier II",family="Amplifier",has_ability=false,incoming_text="",recast=0},
[33] = {slot_id=338495,maneuver="Ice Maneuver",name="Loudspeaker V",family="Loudspeaker",has_ability=false,incoming_text="",recast=0},
[34] = {slot_id=348496,maneuver="Ice Maneuver",name="Tranquilizer IV",family="Tranquilizer",has_ability=false,incoming_text="",recast=0},
[35] = {slot_id=358497,maneuver="Ice Maneuver",name="Arcanoclutch",family="Arcanoclutch",has_ability=false,incoming_text="",recast=0},
[36] = {slot_id=368498,maneuver="Ice Maneuver",name="Arcanoclutch II",family="Arcanoclutch",has_ability=false,incoming_text="",recast=0},
[37] = {slot_id=378513,maneuver="Wind Maneuver",name="Accelerator",family="Accelerator",has_ability=false,incoming_text="",recast=0},
[38] = {slot_id=388514,maneuver="Wind Maneuver",name="Scope",family="Scope",has_ability=false,incoming_text="",recast=0},
[39] = {slot_id=398515,maneuver="Wind Maneuver",name="Pattern Reader",family="Pattern Reader",has_ability=false,incoming_text="",recast=0},
[40] = {slot_id=408516,maneuver="Wind Maneuver",name="Accelerator II",family="Accelerator",has_ability=false,incoming_text="",recast=0},
[41] = {slot_id=418517,maneuver="Wind Maneuver",name="Drum Magazine",family="Drum Magazine",has_ability=false,incoming_text="",recast=0},
[42] = {slot_id=428518,maneuver="Wind Maneuver",name="Turbo Charger",family="Turbo Charger",has_ability=false,incoming_text="",recast=0},
[43] = {slot_id=438519,maneuver="Wind Maneuver",name="Replicator",family="Replicator",has_ability=true,incoming_text="Unknown",recast=60},
[44] = {slot_id=448520,maneuver="Wind Maneuver",name="Barrage Turbine",family="Barrage Turbine",has_ability=true,incoming_text="Unknown",recast=180},
[45] = {slot_id=458521,maneuver="Wind Maneuver",name="Turbo Charger II",family="Turbo Charger",has_ability=false,incoming_text="",recast=0},
[46] = {slot_id=468522,maneuver="Wind Maneuver",name="Accelerator III",family="Accelerator",has_ability=false,incoming_text="",recast=0},
[47] = {slot_id=478523,maneuver="Wind Maneuver",name="Scope II",family="Scope",has_ability=false,incoming_text="",recast=0},
[48] = {slot_id=488524,maneuver="Wind Maneuver",name="Repeater",family="Repeater",has_ability=false,incoming_text="",recast=0},
[49] = {slot_id=498525,maneuver="Wind Maneuver",name="Accelerator IV",family="Accelerator",has_ability=false,incoming_text="",recast=0},
[50] = {slot_id=508526,maneuver="Wind Maneuver",name="Scope III",family="Scope",has_ability=false,incoming_text="",recast=0},
[51] = {slot_id=518527,maneuver="Wind Maneuver",name="Scope IV",family="Scope",has_ability=false,incoming_text="",recast=0},
[52] = {slot_id=528528,maneuver="Wind Maneuver",name="truesights",family="truesights",has_ability=false,incoming_text="",recast=0},
[53] = {slot_id=538545,maneuver="Earth Maneuver",name="Shock Absorber",family="Shock Absorber",has_ability=true,incoming_text="Unknown",recast=180},
[54] = {slot_id=548546,maneuver="Earth Maneuver",name="Armor Plate",family="Armor Plate",has_ability=false,incoming_text="",recast=0},
[55] = {slot_id=558547,maneuver="Earth Maneuver",name="Analyzer",family="Analyzer",has_ability=false,incoming_text="",recast=0},
[56] = {slot_id=568548,maneuver="Earth Maneuver",name="Armor Plate II",family="Armor Plate",has_ability=false,incoming_text="",recast=0},
[57] = {slot_id=578549,maneuver="Earth Maneuver",name="Equalizer",family="Equalizer",has_ability=false,incoming_text="",recast=0},
[58] = {slot_id=588550,maneuver="Earth Maneuver",name="Schurzen",family="Schurzen",has_ability=false,incoming_text="",recast=0},
[59] = {slot_id=598551,maneuver="Earth Maneuver",name="Hammermill",family="Hammermill",has_ability=false,incoming_text="",recast=0},
[60] = {slot_id=608552,maneuver="Earth Maneuver",name="Barrier Module II",family="Barrier Module",has_ability=true,incoming_text="Unknown",recast=180},
[61] = {slot_id=618553,maneuver="Earth Maneuver",name="Shock Absorber II",family="Shock Absorber",has_ability=true,incoming_text="Unknown",recast=180},
[62] = {slot_id=628554,maneuver="Earth Maneuver",name="Armor Plate III",family="Armor Plate",has_ability=false,incoming_text="",recast=0},
[63] = {slot_id=638555,maneuver="Earth Maneuver",name="Barrier Module",family="Barrier Module",has_ability=true,incoming_text="Unknown",recast=180},
[64] = {slot_id=648556,maneuver="Earth Maneuver",name="Armor Plate IV",family="Armor Plate",has_ability=false,incoming_text="",recast=0},
[65] = {slot_id=658557,maneuver="Earth Maneuver",name="Shock Absorber III",family="Shock Absorber",has_ability=true,incoming_text="Unknown",recast=180},
[66] = {slot_id=668577,maneuver="Earth Maneuver",name="Stabilizer",family="Stabilizer",has_ability=false,incoming_text="",recast=0},
[67] = {slot_id=678578,maneuver="Thunder Maneuver",name="Volt Gun",family="Volt Gun",has_ability=false,incoming_text="",recast=0},
[68] = {slot_id=688579,maneuver="Thunder Maneuver",name="Heat Seeker",family="Heat Seeker",has_ability=false,incoming_text="",recast=0},
[69] = {slot_id=698580,maneuver="Thunder Maneuver",name="Stabilizer II",family="Stabilizer",has_ability=false,incoming_text="",recast=0},
[70] = {slot_id=708581,maneuver="Thunder Maneuver",name="Target Marker",family="Target Marker",has_ability=false,incoming_text="",recast=0},
[71] = {slot_id=718582,maneuver="Thunder Maneuver",name="Dynamo",family="Dynamo",has_ability=false,incoming_text="",recast=0},
[72] = {slot_id=728583,maneuver="Thunder Maneuver",name="Coiler",family="Coiler",has_ability=false,incoming_text="",recast=0},
[73] = {slot_id=738584,maneuver="Thunder Maneuver",name="Galvanizer",family="Galvanizer",has_ability=false,incoming_text="",recast=0},
[74] = {slot_id=748585,maneuver="Thunder Maneuver",name="Stabilizer III",family="Stabilizer",has_ability=false,incoming_text="",recast=0},
[75] = {slot_id=758586,maneuver="Thunder Maneuver",name="Coiler II",family="Coiler",has_ability=false,incoming_text="",recast=0},
[76] = {slot_id=768587,maneuver="Thunder Maneuver",name="Dynamo II",family="Dynamo",has_ability=false,incoming_text="",recast=0},
[77] = {slot_id=778588,maneuver="Thunder Maneuver",name="Stabilizer IV",family="Stabilizer",has_ability=false,incoming_text="",recast=0},
[78] = {slot_id=788589,maneuver="Thunder Maneuver",name="Dynamo III",family="Dynamo",has_ability=false,incoming_text="",recast=0},
[79] = {slot_id=798590,maneuver="Thunder Maneuver",name="Stabilizer V",family="Stabilizer",has_ability=false,incoming_text="",recast=0},
[80] = {slot_id=808609,maneuver="Water Maneuver",name="Mana Jammer",family="Mana Jammer",has_ability=false,incoming_text="",recast=0},
[81] = {slot_id=818610,maneuver="Water Maneuver",name="Heatsink",family="Heatsink",has_ability=false,incoming_text="",recast=0},
[82] = {slot_id=828611,maneuver="Water Maneuver",name="Stealth Screen",family="Stealth Screen",has_ability=false,incoming_text="",recast=0},
[83] = {slot_id=838612,maneuver="Water Maneuver",name="Mana Jammer II",family="Mana Jammer",has_ability=false,incoming_text="",recast=0},
[84] = {slot_id=848613,maneuver="Water Maneuver",name="Mana Channeler",family="Mana Channeler",has_ability=false,incoming_text="",recast=0},
[85] = {slot_id=858614,maneuver="Water Maneuver",name="Condenser",family="Condenser",has_ability=false,incoming_text="",recast=0},
[86] = {slot_id=868615,maneuver="Water Maneuver",name="Steam Jacket",family="Steam Jacket",has_ability=false,incoming_text="",recast=0},
[87] = {slot_id=878616,maneuver="Water Maneuver",name="Percolator",family="Percolator",has_ability=false,incoming_text="",recast=0},
[88] = {slot_id=888617,maneuver="Water Maneuver",name="Mana Jammer III",family="Mana Jammer",has_ability=false,incoming_text="",recast=0},
[89] = {slot_id=898618,maneuver="Water Maneuver",name="Stealth Screen II",family="Stealth Screen",has_ability=false,incoming_text="",recast=0},
[90] = {slot_id=908619,maneuver="Water Maneuver",name="Resister",family="Resister",has_ability=false,incoming_text="",recast=0},
[91] = {slot_id=918620,maneuver="Water Maneuver",name="Resister II",family="Resister",has_ability=false,incoming_text="",recast=0},
[92] = {slot_id=928621,maneuver="Water Maneuver",name="Mana Jammer IV",family="Mana Jammer",has_ability=false,incoming_text="",recast=0},
[93] = {slot_id=938622,maneuver="Water Maneuver",name="Mana Channeler II",family="Mana Channeler",has_ability=false,incoming_text="",recast=0},
[94] = {slot_id=948641,maneuver="Light Maneuver",name="Auto-Repair Kit",family="Auto-Repair Kit",has_ability=false,incoming_text="",recast=0},
[95] = {slot_id=958642,maneuver="Light Maneuver",name="Flashbulb",family="Flashbulb",has_ability=true,incoming_text="Flashbulb",recast=45},
[96] = {slot_id=968643,maneuver="Light Maneuver",name="Damage Gauge",family="Damage Gauge",has_ability=false,incoming_text="",recast=0},
[97] = {slot_id=978644,maneuver="Light Maneuver",name="Auto-Repair Kit II",family="Auto-Repair Kit",has_ability=false,incoming_text="",recast=0},
[98] = {slot_id=988645,maneuver="Light Maneuver",name="Eraser",family="Eraser",has_ability=true,incoming_text="Unknown",recast=30},
[99] = {slot_id=998646,maneuver="Light Maneuver",name="Optic Fiber",family="Optic Fiber",has_ability=false,incoming_text="",recast=0},
[100] = {slot_id=1008648,maneuver="Light Maneuver",name="Vivi-Valve",family="Vivi-Valve",has_ability=false,incoming_text="",recast=0},
[101] = {slot_id=1018649,maneuver="Light Maneuver",name="Vivi-Valve II",family="Vivi-Valve",has_ability=false,incoming_text="",recast=0},
[102] = {slot_id=1028650,maneuver="Light Maneuver",name="Auto-Repair Kit III",family="Auto-Repair Kit",has_ability=false,incoming_text="",recast=0},
[103] = {slot_id=1038651,maneuver="Light Maneuver",name="Arcanic Cell",family="Arcanic Cell",has_ability=false,incoming_text="",recast=0},
[104] = {slot_id=1048652,maneuver="Light Maneuver",name="Arcanic Cell II",family="Arcanic Cell",has_ability=false,incoming_text="",recast=0},
[105] = {slot_id=1058653,maneuver="Light Maneuver",name="Auto-Repair Kit IV",family="Auto-Repair Kit",has_ability=false,incoming_text="",recast=0},
[106] = {slot_id=1068654,maneuver="Light Maneuver",name="Optic Fiber II",family="Optic Fiber",has_ability=false,incoming_text="",recast=0},
[107] = {slot_id=1078655,maneuver="Light Maneuver",name="Damage Gauge II",family="Damage Gauge",has_ability=false,incoming_text="",recast=0},
[108] = {slot_id=1088673,maneuver="Dark Maneuver",name="Mana Tank",family="Mana Tank",has_ability=false,incoming_text="",recast=0},
[109] = {slot_id=1098674,maneuver="Dark Maneuver",name="Mana Converter",family="Mana Converter",has_ability=true,incoming_text="Unknown",recast=180},
[110] = {slot_id=1108675,maneuver="Dark Maneuver",name="Mana Conserver",family="Mana Conserver",has_ability=false,incoming_text="",recast=0},
[111] = {slot_id=1118676,maneuver="Dark Maneuver",name="Mana Tank II",family="Mana Tank",has_ability=false,incoming_text="",recast=0},
[112] = {slot_id=1128677,maneuver="Dark Maneuver",name="Smoke Screen",family="Smoke Screen",has_ability=false,incoming_text="",recast=0},
[113] = {slot_id=1138678,maneuver="Dark Maneuver",name="Economizer",family="Economizer",has_ability=true,incoming_text="Unknown",recast=180},
[114] = {slot_id=1148680,maneuver="Dark Maneuver",name="Disruptor",family="Disruptor",has_ability=true,incoming_text="Unknown",recast=60},
[115] = {slot_id=1158681,maneuver="Dark Maneuver",name="Mana Tank III",family="Mana Tank",has_ability=false,incoming_text="",recast=0},
[116] = {slot_id=1168682,maneuver="Dark Maneuver",name="Regulator",family="Regulator",has_ability=false,incoming_text="",recast=0},
[117] = {slot_id=1178683,maneuver="Dark Maneuver",name="Mana Tank IV",family="Mana Tank",has_ability=false,incoming_text="",recast=0},
}